import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>TMBC - ADMIN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logoBox}>
          <Image
            className={styles.logo}
            src="/tmbc.svg"
            alt="tmbc Logo"
            width={180}
            height={37}
            priority
          />
        </div>
        <div className={styles.title}>
          <h2>ADMIN</h2>
        </div>
        <div className={styles.links}>
          <Link href="/danna-paola/tour" className={styles.link}>
            Danna Paola
          </Link>
          <Link href="/" className={`${styles.link} ${styles.disabled}`}>
            Molotov
          </Link>
          <Link href="/" className={`${styles.link} ${styles.disabled}`}>
            Alex Hoyer
          </Link>
          <Link href="/" className={`${styles.link} ${styles.disabled}`}>
            Mario Bautista
          </Link>
        </div>
      </main>
    </>
  );
}
